# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python Linting

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  REF_NAME: ${{ github.head_ref || github.ref_name }}

jobs:
  validate:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.11", "3.12", "3.13"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip poetry
        poetry config virtualenvs.in-project true
        poetry config virtualenvs.create true
        poetry --version
        poetry install --no-root
    - name: Lint with black
      run: |
        poetry run black -t py310 --check src/
    - name: Type Lint with mypy
      run: |
        poetry run mypy -v src/
    - name: Build package
      run: |
        poetry build
    - name: 'Upload PythonPackage Artifact'
      uses: actions/upload-artifact@v4
      if: ${{ github.event_name == 'push' }} # only: main and on merge.
      with:
        name: "pyccu3-sdist"
        path: dist/*
        retention-days: 30
        overwrite: true
        if-no-files-found: error
    - name: Pytest
      run: |
        echo "This should later run the unit tests."